enabled: true
favicon:
  user/themes/big-picture/images/images.png:
    name: images.png
    type: image/png
    size: 3172
    path: user/themes/big-picture/images/images.png
error_background_image:
  user/themes/big-picture/images/error.jpg:
    name: error.jpg
    type: image/jpeg
    size: 75827
    path: user/themes/big-picture/images/error.jpg
